# Generated by Django 4.2.23 on 2025-08-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "rsvp_status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("maybe", "Maybe"),
                        ],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("plus_one", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="profiles.weddingprofile",
                    ),
                ),
            ],
        ),
    ]
